apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-nginx-init 
  
spec:
  replicas: 1 
  selector: 
    matchLabels:
      app: web-init
  template: 
    metadata:
      labels: 
        app: web-init
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.2
      initContainers:
      - name: init-busybox
        image: busybox
        command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
