apiVersion: apps/v1
kind: Deployment
metadata:
  name: netology-deployment
  labels:
    app: main1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main1
  template:
    metadata:
      labels:
        app: main1
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.1
        ports:
        - containerPort: 80

      - name: network-multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "11443"
        ports:
        - containerPort: 8080
          name: http-port
        - containerPort: 11443
          name: https-port
        resources:
          requests:
            cpu: "1m"
            memory: "20Mi"
          limits:
            cpu: "10m"
            memory: "20Mi"
